/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulator.jumlahHari;
import kalkulator.jumlahHari.MenghitungJumlahHari;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import static kalkulator.jumlahHari.MenghitungJumlahHari.Hitung;
/**
 *
 * @author Marsy
 */
public class apkJumlahHari extends javax.swing.JFrame {

    private String getHari;

    /**
     * Creates new form apkJumlahHari
     */
    public apkJumlahHari() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Tahun = new javax.swing.JTextField();
        Bulan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        HasilAkhir = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BtnHitung = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnSimpan = new javax.swing.JButton();
        BtnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penentu Jumlah hari");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(187, 253, 253));
        jPanel2.setLayout(null);

        Tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunActionPerformed(evt);
            }
        });
        jPanel2.add(Tahun);
        Tahun.setBounds(170, 22, 187, 22);

        Bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        jPanel2.add(Bulan);
        Bulan.setBounds(170, 62, 187, 22);

        jLabel1.setText("Tahun");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(52, 25, 90, 16);

        jLabel2.setText("Bulan");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(52, 65, 90, 16);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(18, 33, 400, 110);

        jPanel3.setBackground(new java.awt.Color(252, 175, 213));
        jPanel3.setLayout(null);

        HasilAkhir.setBackground(new java.awt.Color(255, 255, 255));
        HasilAkhir.setText("jLabel3");
        jPanel3.add(HasilAkhir);
        HasilAkhir.setBounds(16, 22, 355, 16);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(18, 155, 400, 70);

        jPanel4.setBackground(new java.awt.Color(162, 253, 162));
        jPanel4.setLayout(null);

        BtnHitung.setText("Hitung");
        BtnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHitungActionPerformed(evt);
            }
        });
        jPanel4.add(BtnHitung);
        BtnHitung.setBounds(20, 17, 70, 23);

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        jPanel4.add(BtnHapus);
        BtnHapus.setBounds(116, 17, 65, 23);

        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        jPanel4.add(BtnSimpan);
        BtnSimpan.setBounds(211, 17, 72, 23);

        BtnKeluar.setText("Keluar");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        jPanel4.add(BtnKeluar);
        BtnKeluar.setBounds(313, 17, 65, 23);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 240, 400, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        String tanya = "Yakin akan keluar?";
        boolean yakin = JOptionPane. showConfirmDialog(rootPane, tanya) 
                == JOptionPane.YES_OPTION;
        if(yakin){
        System.exit(0);
    }
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void TahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunActionPerformed

    private void BtnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHitungActionPerformed
        // TODO add your handling code here:
        try {
            int tahun = Integer.parseInt(Tahun.getText());
            String bulan = Bulan.getSelectedItem().toString();
            MenghitungJumlahHari hitungHari = new MenghitungJumlahHari();
            HasilAkhir.setText("Jumlah hari pada bulan " + Bulan + " tahun " + Tahun + " adalah " + getHari);
            HasilAkhir.setText(getHari);
        } catch (NumberFormatException e) {
            HasilAkhir.setText("Invalid");
        }
    }//GEN-LAST:event_BtnHitungActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        Tahun.setText("");
        Bulan.setSelectedIndex(0);
        HasilAkhir.setText("Jumlah Hari...");
        Tahun.requestFocus();
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        // TODO add your handling code here:
        prosesSimpan();
         try (BufferedWriter writer = new BufferedWriter(new FileWriter("hasil_perhitungan.txt", true))) {
            writer.write("Tahun: " + Tahun.getText() + ", Bulan: " + Bulan.getSelectedItem().toString() + ", Hasil: " + HasilAkhir.getText());
            writer.newLine();
            writer.flush();
            HasilAkhir.setText("Hasil perhitungan disimpan.");
        } catch (IOException e) {
            HasilAkhir.setText("Gagal menyimpan hasil.");}
    }//GEN-LAST:event_BtnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apkJumlahHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apkJumlahHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apkJumlahHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apkJumlahHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apkJumlahHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnHitung;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JComboBox<String> Bulan;
    private javax.swing.JLabel HasilAkhir;
    private javax.swing.JTextField Tahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    private void prosesSimpan() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
